### ISSUE TITLE
Add User Social informations in the Configuration History Timeline

### ISSUE THREAD

**Issue by romone22** [Tailer-Platform/tailer-studio#199]
**Is your feature request related to a problem? Please describe.**
Currently, in the configuration history timeline, we can see the email of who has pushed the last version and, in the listing, the date of the previous updated/created versions of the configuration. 
We can't see who pushed the previous  versions of the configuration.

**Describe the solution you'd like**
For each configuration's versions, add the Social Picture, followed by First & Last Names. Just Below, add the datetime of the configuration's version. Use relative Moment Date (as Last 2mn) for recent date.

For the current version, add also Social Picture, First and last Name and the datetime. 

**Describe alternatives you've considered**

**Additional context**
The UI of the versions history must be not eavy

**Comment by Eronne** [comment]
This will be added in #285
