### ISSUE TITLE
Provide data in local env

### ISSUE THREAD

**Issue by Eronne** [Tailer-Platform/tailer-studio#226]
**Is your feature request related to a problem? Please describe.**
When running the app in local with firebase emulators, there is actually no way to have data.

**Describe the solution you'd like**
Import production backups in local.
Links:
- [Export and import data](https://firebase.google.com/docs/firestore/manage-data/export-import)
- [How do import data from cloud firestore to the local emulator?](https://stackoverflow.com/questions/57838764/how-do-import-data-from-cloud-firestore-to-the-local-emulator)

**Comment by romone22** [comment]
No more matter
