### ISSUE TITLE
Add Client Type And Client Version used for a TTT Conf and Run

### ISSUE THREAD

**Issue by romone22** [Tailer-Platform/tailer-studio#251]
**Is your feature request related to a problem? Please describe.**
Currently, it's not possible to know which version of the SDK was used to push a TTT configuration into Jarvis Manager. 

However, new Jarvis SDK versions are frequently deployed with new features and in order to get this news features (as status of a task run), the user must redeploy his configuration with the new version of the SDK. 

So, we need, to see and inform the user in Jarvis Studio about the version of the SDK used to push the configuration and alert him if needed (we will see that in another issue). 

**Describe the solution you'd like**
From now, the Jarvis is in now adding two new attribut to each TTT Conf and Run: 
- "client_type": by default its "jarvis-sdk" but in the future, other client as jarvis-api could exist
- "client_version": example :  "1.1.3" 

Those two attributs are available : 
- For TTT Conf Doc : At the root of the document
- For TTT Run Doc : In the "configuration_context" payload of the document

For must of the TTT Runs which was not deployed with a SDK version 1.1.3 or above, those two attributs not exist. So they must be added in the Studio UI with those two values : 
- client_type : jarvis-sdk
- client_version : 1.0

In a TTT Run View, those Two attributes must be  displayed in the update cartouche : 
![image](https://user-images.githubusercontent.com/5988677/85197548-f1a92000-b2e1-11ea-9680-d743ce4f0aef.png)

In a TTT Conf View,  those Two attributes must be added in the Configuration Tab, at the End after the Diagram Chart in a new Cartouche named "Client Information"

**Comment by Eronne** [comment]
This has been redescribed in #315
