### ISSUE TITLE
Store Accounts attached to each User in the Users Collections

### ISSUE THREAD

**Issue by romone22** [Tailer-Platform/tailer-studio#271]
**Is your feature request related to a problem? Please describe.**
In the Firestore Users Collection, we can't see the Accounts attached to each user

**Describe the solution you'd like**
Add to the user profile in the Firestore Users Collection the Id (ex: 000010) of each account attached to the user. The accounts should be stored as a MAP object with those informations : 

- Account ID
- Account Name
- Datetime Account added to the user

**Additional context**
FInd a way to propagate the account's name changes from the Firestore Account Collection

**Comment by Eronne** [comment]
Are we implementing this feature of we are waiting the `maestro` migration which handle this by default?
