### ISSUE TITLE
Add on the Signin page a link to reset the password

### ISSUE THREAD

**Issue by romone22** [Tailer-Platform/tailer-studio#293]
**Is your feature request related to a problem? Please describe.**
For those who are signing in Tailer Studio with a email/password, they can't reset their password when needed

**Describe the solution you'd like**
Add a link "Forget your password?" on the login page under the email method to reset the password

**Link**
https://redfern.dev/articles/forgot-password-firebase-vuejs/

**Comment by FelixPr** [comment]
Hi! Our clients start to ask me to open accesses to Tailer Studio to the CGI BI project managers who'll be in charge of the data flows in the new organization. I think this feature to reset the password I'll send to them becomes more and more necessary.
