### ISSUE TITLE
Add Launch option for VM Launcher configuration 

### ISSUE THREAD

**Issue by mathieuhuche** [Tailer-Platform/tailer-studio#309]
I can only run my VM Launcher configuration when I push into Tailer Studio. 
It could be usefull to have the same **Launch** button as TTT configuration.

**Comment by Eronne** [comment]
@FelixPr this can be done with an API call made by @julienguarino I think?

I don't know the technical specs to launch a `vm-launcher` but if it is ok via an API, I can call it on `vm-launcher`.

**Comment by Eronne** [comment]
@julienguarino I tried to launch a DAG from a `vm-launcher` configuration but I had this error : `No DAG account found.`

**Comment by FelixPr** [comment]
You tried to call the API documented [there](https://docs.tailer.ai/tailer-api/api-features) I guess? I see the account should be provided as a parameter. If you tried that and it didn't work, maybe you can provide your API call so @julienguarino can investiguate it
