### ISSUE TITLE
View the client Type and Client Version of the Confs and Runs

### ISSUE THREAD

**Issue by romone22** [Tailer-Platform/tailer-studio#315]
The Tailer SDK is continuously evolving. Each new version includes new features, improves the performance, solves bugs and increases its version number. 
So, it's important to know with which client version the conf is generated to understand the behavior of a run or to activate or not specifics features. 
Moreover, we should be able to warm when a conf must be updated because his client version is now to old to support some new Tailer features. 

**Describe the solution you'd like**
Display in the runs listing, confs listing, run detailed view and conf detailed view the Client Version and the Client Type.
- [x] If those those parameters are not available (for the old confs), they should be set to client_type="tailer-sdk" and client_version = "1.1.0"
- [x] if the client_type = jarvis-sdk it should be displayed as "tailer-sdk"

Here are the rules to get the attributes regarding the conf and run type : 
- [x] STS
  - [x] Conf : root > client_type / configuration_type
  - [x] Run : root > configuration_context  > client_type / configuration_type
- [x] STT
  - [x] Conf : root > client_type / configuration_type
  - [x] Run : root > configuration_context  > client_type / configuration_type
- [x] TTT
  - [x] Conf : root > client_type / configuration_type
  - [x] Run : root > configuration_context  > client_type / configuration_type
- [x] TTS
  - [x] Conf : root > client_type / configuration_type
  - [x] Run : root > configuration_context  > client_type / configuration_type
- [x] VM Launcher
  - [x] Conf : root > client_type / configuration_type
  - [x] Run : root > configuration_context  > configuration > client_type / configuration_type
- [x] Workflow
  - [x] Conf : root > client_type / configuration_type
- [x] Context
  - [x] Conf : root > client_type / configuration_type

The Client Type and Client Version parameters should be displayed in the Context Group in each Run and Conf Detailed View : 
![image](https://user-images.githubusercontent.com/5988677/111903958-bf7d4800-8a44-11eb-85ee-659e4892776b.png)

**Comment by Eronne** [comment]
In the specs, you wrote `configuration_type` but I think it is `client_version` isn't it?
