### ISSUE TITLE
Can't display configuration history

### ISSUE THREAD

**Issue by FelixPr** [Tailer-Platform/tailer-studio#352]
**Describe the bug**
When I click on any configuration history, I see a loading animation but no history at all.

**To Reproduce**
For exemple, go there and click on the datetime link below the name of the last modifier in the upper right corner:
https://studio.tailer.ai/data-operations/storage-to-tables/configurations/mirror-fd-io-exc-gdm-s-vlz-in-input

**Expected behavior**
I should see the history of the configuration's modification.

**Desktop (please complete the following information):**
sec-ch-ua: "Google Chrome";v="95", "Chromium";v="95", ";Not A Brand";v="99"
sec-ch-ua-platform: "macOS"

**Screenshots**
![image.png](https://images.zenhubusercontent.com/6156bff24754f1e4f9d46985/0854a768-7092-46c6-8811-72b110359739)

Last error on:
 POST https://o374453.ingest.sentry.io/api/5206637/store/?sentry_key=1468162210b847ddaeb03fb017d839d9&sentry_version=7

**Comment by Eronne** [comment]
Fix also the `updated_by` property to have email address and not user id.

**Comment by Eronne** [comment]
@julienguarino can we check for this permission error?

**Comment by Eronne** [comment]
@julienguarino I will let you close this issue when rules will be updated ;)

**Comment by julienguarino** [comment]
Done
